Proyectos/Activos/Viaticos_q/3. Ejecución/3.2 Desarrollo/config/routes.rb
Rails.application.routes.draw do
  devise_for :users 
  resources :admins, :controller => "admins"
   match 'admins/:id' => 'admins#destroy', :via => :delete, :as => :admin_destroy
 
  resources :zones do
      resources :proyects do
          resources :spends
          match 'spends/:status' => 'spends#status', :via => :post, :as => :spend_status
          resources :lista
          resources :viaticos
          match 'viaticos/:status' => 'viaticos#status', :via => :post, :as => :viatico_status
          resources :brokers
      end
  end
  

  get 'welcome/index'

  root 'welcome#index'

end

Proyectos/Activos/Viaticos_q/3. Ejecución/3.2 Desarrollo/app/views/admins/index.html.erb
<div class="col-md-10 col-md-offset-1">
  <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  <h2 class="proyect_name alert alert-info">
    <strong>Administracion de Usuarios</strong> 
  </h2>
  <%= link_to ' Crear usuario', new_admin_path, class: "btn btn-primary float_right " %>
  <div class="table-responsive">
    <table class="table table-bordered top">
    <thead>
      <tr>
        <th>Correo de usuario</th>

      </tr>
    </thead>
      <tbody>

        <% @users.each do |user| %>
          <tr>
            <td><%= user.email %></td>
            <td>
              <%= link_to "Eliminar", admin_destroy_path(user), method: :delete, data: { confirm: "El usuario sera eliminado?" }%>
            </td>
          </tr>
        <% end %>

      </tbody>
    </table>
  </div>
  <%= link_to ' Regresar', root_path, class: "btn btn-info float_right " %>
</div>

Proyectos/Activos/Viaticos_q/3. Ejecución/3.2 Desarrollo/app/views/admins/new.html.erb
<div class="col-md-6 col-md-offset-3">
  <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  <h2 class="proyect_name alert alert-info">
    <strong>Registro de usuario</strong> 
  </h2>
  <%= form_for(@user, :url => { :action => "create" } ) do |f| %>
    

    <div class="field">
      <%= f.label :email , "Correo electronico"%><br />
      <%= f.email_field :email, autofocus: true ,class: "form-control"%>
    </div>

    <div class="field">
      <%= f.label :password %>
      <% if @minimum_password_length %>
      <em>(Minimo <%= @minimum_password_length %> caracteres)</em>
      <% end %><br />
      <%= f.password_field :password, autocomplete: "off",class: "form-control" %>
    </div>

    <div class="field">
      <%= f.label :password_confirmation , "Confirmacion de password"%><br />
      <%= f.password_field :password_confirmation, autocomplete: "off" ,class: "form-control"%>
    </div>

    <div class="actions">
      <%= f.submit  "Registrar usuario" %>
    </div>
  <% end %>
  <%= link_to 'regresar', admins_path, class: "btn btn-info fa fa-arrow-left float_right "%> 
</div>