Proyectos/Activos/Viaticos_q/3. Ejecución/3.2 Desarrollo/config/routes.rb
Rails.application.routes.draw do
  devise_for :users 
  resources :admins, :controller => "admins"
   match 'admins/:id' => 'admins#destroy', :via => :delete, :as => :admin_destroy
 
  resources :zones do
      resources :proyects do
          resources :spends
          match 'spends/:status' => 'spends#status', :via => :post, :as => :spend_status
          resources :lista
          resources :viaticos
          match 'viaticos/:status' => 'viaticos#status', :via => :post, :as => :viatico_status
          resources :brokers
      end
  end
  

  get 'welcome/index'

  root 'welcome#index'

end

Proyectos/Activos/Viaticos_q/3. Ejecución/3.2 Desarrollo/app/models/proyect.rb
class Proyect < ActiveRecord::Base
  validates :name, presence: true, uniqueness:  true
  belongs_to :zone
  belongs_to :user
  has_many   :spends
  has_many   :viaticos
  has_many   :brokers
  has_many   :users, through: :brokers
  after_create :save_brokers


  private
  def save_brokers
			Broker.create(user_id: self.user.id,proyect_id: self.id)
  end	
end

Proyectos/Activos/Viaticos_q/3. Ejecución/3.2 Desarrollo/app/controllers/proyects_controller.rb
class ProyectsController < ApplicationController
  before_action :auth
  before_action :set_proyect, only: [:show, :edit, :update, :destroy]
  before_action :set_zone
  before_action :autenticacion_admin!, only: [:destroy]
  
  # GET /proyects
  # GET /proyects.json
 
  
  # GET /proyects/1
  # GET /proyects/1.json
  def show
    zone = Zone.find(params[:zone_id])
    @spends = Spend.paginate(:page => params[:page], :per_page => 20).where("proyect_id = ? AND status = 0",@proyect).order('fecha  DESC')
    @viaticos = Viatico.where("proyect_id = ? AND status = 0",@proyect).order('fecha  DESC')
    @broker = Broker.new
    #2nd you retrieve the comment thanks to params[:id]
    @proyects = zone.proyects.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @proyects }
    end
  end

  # GET /proyects/new
  def new
    @proyect = Proyect.new
    @proyect.zone = @zone

  end

  # GET /proyects/1/edit
  def edit
    zone = Zone.find(params[:zone_id])
    #2nd you retrieve the comment thanks to params[:id]
    @proyects = zone.proyects.find(params[:id])
  end

  # POST /proyects
  # POST /proyects.json
  def create

    @proyect = current_user.proyects.new(proyect_params)
   
    @proyect.zone = @zone
    respond_to do |format|
      if @proyect.save
        format.html { redirect_to [@zone,@proyect], notice: 'Proyect was successfully created.' }
        format.json { render :show, status: :created, location: @proyect }
      else
        format.html { render :new }
        format.json { render json: @proyect.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /proyects/1
  # PATCH/PUT /proyects/1.json
  def update
    respond_to do |format|
      if @proyect.update(proyect_params)
        format.html { redirect_to [@zone,@proyect], notice: 'El proyecto fue actualizado exitosamente' }
        format.json { render :show, status: :ok, location: @proyect }
      else
        format.html { render :edit }
        format.json { render json: @proyect.errors, status: :unprocessable_entity }
      end
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_proyect
      @proyect = Proyect.find(params[:id])
    end
    def set_zone
      @zone = Zone.find(params[:zone_id])
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def proyect_params
      params.require(:proyect).permit(:zone_id, :user_id,:name, :brokers)
    end
end

Proyectos/Activos/Viaticos_q/3. Ejecución/3.2 Desarrollo/app/helpers/proyects_helper.rb
module ProyectsHelper
end

Proyectos/Activos/Viaticos_q/3. Ejecución/3.2 Desarrollo/app/views/proyects/_form.html.erb
<%= form_for([@zone,@proyect]) do |f| %>
  <% if @proyect.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger" role="alert">
          <i class="fa fa-exclamation-circle fa-2x"></i>
          <h2><%= pluralize(@proyect.errors.count, "error") %>Motivos por el cual no se pudo guardar la informacion:</h2>
      </div>

      <% @proyect.errors.full_messages.each do |message| %>
        <div class="alert alert-danger" role="alert">
          <i class="fa fa-exclamation-circle fa-2x"></i>
          <span class="sr-only">Error:</span>
          <%= message %>
        </div>
      <% end %>
    </div>
  <% end %>

  
  <div class="form-group">
    
    <%= f.text_field :name ,placeholder: "Nombre de proyecto", class: "form-control" ,required: "required"%>
  </div>
  
  <div class="actions ">
    <%= f.submit "Guardar" , class: 'btn btn-primary btn-sm guardar' %>
  </div>
<% end %>

Proyectos/Activos/Viaticos_q/3. Ejecución/3.2 Desarrollo/app/views/proyects/edit.html.erb
<div class="col-md-6 col-md-offset-3">
	<p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
	<h2 class="proyect_name alert alert-info">
    	<strong>Editando proyecto</strong> 
  	</h2>
	<div class="space_form">
		<%= render 'form' %>
	</div>
	<%= link_to 'Ir a proyecto', [@zone,@proyect],class: "btn btn-primary" %> 
	<%= link_to ' Regresar', zone_path(@zone), class: "btn btn-info float_right " %>
</div>

Proyectos/Activos/Viaticos_q/3. Ejecución/3.2 Desarrollo/app/views/proyects/index.html.erb
<h1>Listing Proyects </h1>

<table>
  <thead>
    <tr>
      <th>Zone</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @proyects.each do |proyect| %>
      <tr>
        <td><%= proyect.zone.name %></td>
        <td><%= proyect.name %></td>
        <td><%= link_to 'Show', [@zone,proyect] %></td>
        <td><%= link_to 'Edit', edit_zone_proyect_path(@zone, proyect) %></td>
        <td><%= link_to 'Destroy', [@zone,proyect], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Proyect', new_zone_proyect_path(@zone) %>
<%= link_to 'Back', zones_path %>

Proyectos/Activos/Viaticos_q/3. Ejecución/3.2 Desarrollo/app/views/proyects/new.html.erb
<div class="col-md-6 col-md-offset-3">
	<p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
	<h2 class="proyect_name alert alert-info">
    	<strong>Proyecto nuevo</strong> 
  	</h2>
	<div class="space_form">
		<%= render 'form' %>
	</div>
	<%= link_to ' Regresar', zone_path(@zone), class: "btn btn-info float_right " %>
</div>

Proyectos/Activos/Viaticos_q/3. Ejecución/3.2 Desarrollo/app/views/proyects/show.html.erb
<p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
<h2 class="proyect_name alert alert-info">
  <strong><%=@proyect.name%></strong>
  
</h2>
<%= link_to ' Agregar un gasto', new_zone_proyect_spend_path(@zone,@proyect) ,class: "btn btn-primary fa fa-plus edit "%>
<%= link_to ' Agregar un viatico', new_zone_proyect_viatico_path(@zone,@proyect) ,class: "btn btn-info fa fa-money edit "%>
<%if current_user.id == @proyect.user.id || current_user.is_admin?%>
  <%= link_to ' Agregar un Broker', new_zone_proyect_broker_path(@zone,@proyect) ,class: "btn btn-warning fa fa-user edit "%>
<%end%>
<%= link_to ' Regresar', zone_path(@zone) ,class: "btn btn-info fa fa-arrow-left float_right "%>
<%=link_to ' Generar XLS', zone_proyect_spends_path(@zone,@proyect),class: "btn btn-danger fa fa-file-excel-o edit "%>
<div class="table-responsive">
  <table class="table table-bordered">
  	<caption class="top-center">
  		<strong>Lista de Gastos del proyecto</strong>
  	</caption>
    <thead>
      <tr>
        <th>Fecha</th>
        <th>Tipo</th>
        <th>Importe</th>
        <th>Comentarios</th>
        <th>Comprobante</th>
        <th>Numero comprobante</th>
        <th>Usuario</th>
      </tr>
    </thead>

    <tbody>
    	<% @valor = 0 %>
      <% @spends.each do |spend| %>
        
      	<%= render "parcial/color"%>
          <td><%= link_to  spend.fecha ,[@zone,@proyect,spend]%></td>
          <td><%= spend.tipo %></td>
          <td><%= spend.importe %></td>
          <td><%= spend.comntarios %></td>
          <% if spend.comprobante == 1%>
            <td>SI</td>
          <%else%>
            <td>NO</td>
          <%end%>
          <td><%= spend.numero_comprobante %></td>
          <td><%= spend.user.email %></td>
          <%if current_user.is_admin? || current_user.email == spend.user.email%>
            <td><%= link_to "Reportar", zone_proyect_spend_status_path(@zone,@proyect,spend.id), method: :status, data: { confirm: "Deseas continuar?" }%>
            </td>
            <td><%= link_to 'Editar', edit_zone_proyect_spend_path(@zone,@proyect,spend) %></td>
          <%end%>
          <%if current_user.is_admin?%>
          <td><%= link_to 'Eliminar', [@zone,@proyect,spend], method: :delete, data: { confirm: 'Estas seguro?' } %></td>
          <%end%>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= will_paginate @spends %> 
</div>

<div class="table-responsive">
  <table class="table table-bordered spacedor">
    <caption class="top-center">
      <strong>Lista de Viaticos del proyecto</strong>
    </caption>
    <thead>
      <tr>
        <th>Fecha</th>
        <th>Creador</th>
        <th>Cantidad</th>
      </tr>
    </thead>

    <tbody>
      <% @valor = 0 %>
      <% @viaticos.each do |viatico| %>
        <%= render "parcial/color"%>
          
          <td><%= link_to viatico.fecha, [@zone,@proyect,viatico]%></td>
          <td><%= viatico.user.email %></td>
          <td><%= viatico.cantidad %></td>
          <%if current_user.is_admin? || current_user.email == viatico.user.email%>
          <td><%= link_to "Reportar", zone_proyect_viatico_status_path(@zone,@proyect,viatico.id), method: :status, data: { confirm: "Deseas continuar?" }%>
            </td>
          <td><%= link_to 'Editar', edit_zone_proyect_viatico_path(@zone,@proyect,viatico) %></td>
          <%end%>
          <%if current_user.is_admin?%>
          <td><%= link_to 'Eliminar', [@zone,@proyect,viatico], method: :delete, data: { confirm: 'Estas seguro?' } %></td>
          <%end%>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<div class="col-md-12">
  <div class="col-md-6 col-md-offset-3">
    <div class="table-responsive">
      <table class="table table-bordered spacedor">
        <caption class="top-center">
          <strong>Lista de colaboradores del proyecto</strong>
        </caption>
        <thead>
          <tr>
            <th>Correo de colaborador</th>
          </tr>
        </thead>

        <tbody>
          <% @valor = 0 %>
          <% @proyect.brokers.each do |broker| %>
            <%= render "parcial/color"%>
              <td><%= broker.user.email %></td>
              <%if current_user.email == @proyect.user.email || current_user.is_admin?%>
              <td><%= link_to 'Eliminar', [@zone,@proyect,broker], method: :delete, data: { confirm: 'Estas seguro?' } %></td>
              <%end%>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>
<%if current_user.is_admin? || current_user.email == @proyect.user.email%>
<%= link_to ' Editar', edit_zone_proyect_path(@zone,@proyect) ,class: "btn btn-warning fa fa-edit"%>
<%end%>
<%=link_to ' Gastos Realizados', zone_proyect_lista_path(@zone,@proyect),class: "btn btn-success fa fa-usd edit"%>
<%=link_to ' Viaticos Solicitados', zone_proyect_viaticos_path(@zone,@proyect),class: "btn btn-success fa fa-money edit "%>